"use client";

import { useGlowAnimation } from "@/src/app/study/hooks/useGlowAnimation";
import { useAnswerSubmission } from "@/src/app/study/hooks/useAnswerSubmission";

interface QuestionnaireCardProps {
  question: string;
}

export function QuestionnaireCard({ question }: QuestionnaireCardProps) {
  const showGlow = useGlowAnimation(1200);

  const {
    answer,
    isSubmitting,
    isSubmitted,
    handleAnswerChange,
    submitAnswer,
    editAnswer,
  } = useAnswerSubmission();

  return (
    <div className="w-full">
      <div className="relative p-[2px] rounded-3xl overflow-hidden shadow-xl shadow-black/5">
        
        {/* Animated Glow Border */}
        <div
          className={`absolute inset-0 rounded-3xl transition-opacity duration-700 ${
            showGlow ? "opacity-100" : "opacity-0"
          }`}
        >
          <div className="absolute inset-[-50%] animate-border-flow bg-[conic-gradient(from_0deg,#3b82f6,#f97316,#eab308,#22c55e,#3b82f6)]" />
        </div>

        {/* Inner Content Box */}
        <div className="relative rounded-[22px] bg-white p-8 sm:p-10">
          
          {/* Badge */}
          <div className="flex items-center justify-between">
            <span className="inline-block rounded-full bg-[#fde9e7] px-3.5 py-1 text-xs font-bold text-[#752b26]">
              Question Generated by LearnIA
            </span>
          </div>

          {/* Question Text */}
          <p className="mt-6 text-xl sm:text-2xl font-bold text-[#752b26] leading-relaxed">
            "{question}"
          </p>

          {/* Answer Section */}
          <div className="mt-8 pt-6 border-t border-stone-100">
            <label className="block text-xs font-bold uppercase tracking-wider text-[#752b26]/70 mb-2">
              Your Answer
            </label>

            <textarea
              rows={4}
              disabled={isSubmitted || isSubmitting}
              value={answer}
              onChange={(e) => handleAnswerChange(e.target.value)}
              placeholder="Type your answer here based on the document..."
              className={`w-full rounded-2xl border p-4 text-sm text-stone-800 placeholder-stone-400 outline-none transition-all resize-none ${
                isSubmitted
                  ? "bg-stone-50 border-emerald-300 text-stone-600"
                  : "bg-[#faf8f7] border-stone-200 focus:border-[#752b26] focus:ring-2 focus:ring-[#752b26]/10"
              }`}
            />

            {/* Actions Bar */}
            <div className="mt-4 flex items-center justify-between">
              <div>
                {isSubmitted && (
                  <span className="inline-flex items-center gap-1.5 text-xs font-bold text-emerald-600">
                    <span className="h-2 w-2 rounded-full bg-emerald-500" />
                    Answer submitted successfully!
                  </span>
                )}
              </div>

              <div className="flex items-center gap-3">
                {isSubmitted ? (
                  <button
                    type="button"
                    onClick={editAnswer}
                    className="rounded-full px-5 py-2 text-xs font-semibold text-stone-500 hover:text-[#752b26] transition-colors"
                  >
                    Edit answer
                  </button>
                ) : (
                  <button
                    type="button"
                    disabled={!answer.trim() || isSubmitting}
                    onClick={submitAnswer}
                    className="rounded-full border border-[#f5c6c1] bg-[#fde9e7] px-6 py-2.5 text-xs font-bold text-[#752b26] shadow-sm transition-all hover:scale-105 active:scale-95 disabled:opacity-50 disabled:pointer-events-none cursor-pointer"
                  >
                    {isSubmitting ? "Submitting..." : "Submit Answer"}
                  </button>
                )}
              </div>
            </div>

          </div>

        </div>

      </div>
    </div>
  );
}